// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Query(arg1, arg2, arg3) {
  return window['go']['dbs']['MysqlProxy']['Query'](arg1, arg2, arg3);
}

export function Register(arg1, arg2) {
  return window['go']['dbs']['MysqlProxy']['Register'](arg1, arg2);
}
