// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dbs} from '../models';

export function Query(arg1:string,arg2:string,arg3:Array<any>):Promise<dbs.SqlResult|Error>;

export function Register(arg1:string,arg2:dbs.PostgresqlOpts):void;
