// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HLen(arg1, arg2) {
  return window['go']['dbs']['RedisProxy']['HLen'](arg1, arg2);
}

export function LInsertAfter(arg1, arg2, arg3, arg4) {
  return window['go']['dbs']['RedisProxy']['LInsertAfter'](arg1, arg2, arg3, arg4);
}

export function BitOpAnd(arg1, arg2, arg3) {
  return window['go']['dbs']['RedisProxy']['BitOpAnd'](arg1, arg2, arg3);
}

export function BitOpNot(arg1, arg2, arg3) {
  return window['go']['dbs']['RedisProxy']['BitOpNot'](arg1, arg2, arg3);
}

export function BitOpXor(arg1, arg2, arg3) {
  return window['go']['dbs']['RedisProxy']['BitOpXor'](arg1, arg2, arg3);
}

export function Exists(arg1, arg2) {
  return window['go']['dbs']['RedisProxy']['Exists'](arg1, arg2);
}

export function SetBit(arg1, arg2, arg3, arg4) {
  return window['go']['dbs']['RedisProxy']['SetBit'](arg1, arg2, arg3, arg4);
}

export function Unlink(arg1, arg2) {
  return window['go']['dbs']['RedisProxy']['Unlink'](arg1, arg2);
}

export function Expire(arg1, arg2, arg3, arg4) {
  return window['go']['dbs']['RedisProxy']['Expire'](arg1, arg2, arg3, arg4);
}

export function GetBit(arg1, arg2, arg3) {
  return window['go']['dbs']['RedisProxy']['GetBit'](arg1, arg2, arg3);
}

export function LInsertBefore(arg1, arg2, arg3, arg4) {
  return window['go']['dbs']['RedisProxy']['LInsertBefore'](arg1, arg2, arg3, arg4);
}

export function LLen(arg1, arg2) {
  return window['go']['dbs']['RedisProxy']['LLen'](arg1, arg2);
}

export function Del(arg1, arg2) {
  return window['go']['dbs']['RedisProxy']['Del'](arg1, arg2);
}

export function HDel(arg1, arg2, arg3) {
  return window['go']['dbs']['RedisProxy']['HDel'](arg1, arg2, arg3);
}

export function Incr(arg1, arg2) {
  return window['go']['dbs']['RedisProxy']['Incr'](arg1, arg2);
}

export function Register(arg1, arg2) {
  return window['go']['dbs']['RedisProxy']['Register'](arg1, arg2);
}

export function BitCount(arg1, arg2, arg3, arg4) {
  return window['go']['dbs']['RedisProxy']['BitCount'](arg1, arg2, arg3, arg4);
}

export function BitOpOr(arg1, arg2, arg3) {
  return window['go']['dbs']['RedisProxy']['BitOpOr'](arg1, arg2, arg3);
}

export function BitPos(arg1, arg2, arg3, arg4) {
  return window['go']['dbs']['RedisProxy']['BitPos'](arg1, arg2, arg3, arg4);
}

export function DecrBy(arg1, arg2, arg3) {
  return window['go']['dbs']['RedisProxy']['DecrBy'](arg1, arg2, arg3);
}

export function Keys(arg1, arg2) {
  return window['go']['dbs']['RedisProxy']['Keys'](arg1, arg2);
}

export function Decr(arg1, arg2) {
  return window['go']['dbs']['RedisProxy']['Decr'](arg1, arg2);
}

export function HIncrBy(arg1, arg2, arg3, arg4) {
  return window['go']['dbs']['RedisProxy']['HIncrBy'](arg1, arg2, arg3, arg4);
}

export function HSet(arg1, arg2, arg3) {
  return window['go']['dbs']['RedisProxy']['HSet'](arg1, arg2, arg3);
}

export function IncrBy(arg1, arg2, arg3) {
  return window['go']['dbs']['RedisProxy']['IncrBy'](arg1, arg2, arg3);
}
