// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Unregister(arg1) {
  return window['go']['dbs']['SqlProxy']['Unregister'](arg1);
}

export function Commit(arg1, arg2) {
  return window['go']['dbs']['SqlProxy']['Commit'](arg1, arg2);
}

export function Query(arg1, arg2, arg3) {
  return window['go']['dbs']['SqlProxy']['Query'](arg1, arg2, arg3);
}

export function RegisterMysql(arg1, arg2) {
  return window['go']['dbs']['SqlProxy']['RegisterMysql'](arg1, arg2);
}

export function RegisterPostgresql(arg1, arg2) {
  return window['go']['dbs']['SqlProxy']['RegisterPostgresql'](arg1, arg2);
}

export function Rollback(arg1, arg2) {
  return window['go']['dbs']['SqlProxy']['Rollback'](arg1, arg2);
}

export function TestMysql(arg1) {
  return window['go']['dbs']['SqlProxy']['TestMysql'](arg1);
}

export function TestPostgresql(arg1) {
  return window['go']['dbs']['SqlProxy']['TestPostgresql'](arg1);
}
