// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NewMysqlDatabase(arg1, arg2) {
  return window['go']['main']['App']['NewMysqlDatabase'](arg1, arg2);
}

export function NewPostgresqlDatabase(arg1, arg2) {
  return window['go']['main']['App']['NewPostgresqlDatabase'](arg1, arg2);
}

export function QueryDatabaseExtOpts(arg1, arg2) {
  return window['go']['main']['App']['QueryDatabaseExtOpts'](arg1, arg2);
}

export function Root() {
  return window['go']['main']['App']['Root']();
}

export function UpdateDatabaseExtOpts(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDatabaseExtOpts'](arg1, arg2, arg3);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DropDatabase(arg1, arg2) {
  return window['go']['main']['App']['DropDatabase'](arg1, arg2);
}

export function ListDatabases(arg1) {
  return window['go']['main']['App']['ListDatabases'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function NewRedisDatabase(arg1, arg2) {
  return window['go']['main']['App']['NewRedisDatabase'](arg1, arg2);
}

export function SetColor(arg1, arg2) {
  return window['go']['main']['App']['SetColor'](arg1, arg2);
}
