// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SetColor(arg1:string,arg2:string):void;

export function TryLock():Promise<boolean>;

export function Unlock():void;

export function CreateProject(arg1:string):Promise<Error>;

export function ListDatabases(arg1:string):Promise<Array<main.DBInfo>|Error>;

export function ListProjects():Promise<Array<main.ProjectListItem>|Error>;

export function Lock():void;

export function Root():Promise<string>;
