// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetColor(arg1, arg2) {
  window['go']['main']['App']['SetColor'](arg1, arg2);
}

export function TryLock() {
  return window['go']['main']['App']['TryLock']();
}

export function Unlock() {
  window['go']['main']['App']['Unlock']();
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function ListDatabases(arg1) {
  return window['go']['main']['App']['ListDatabases'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function Lock() {
  window['go']['main']['App']['Lock']();
}

export function Root() {
  return window['go']['main']['App']['Root']();
}
