// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function Root() {
  return window['go']['main']['App']['Root']();
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}
