// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProject(arg1:string):Promise<Error>;

export function ListProjects():Promise<main.Projects|Error>;

export function Root():Promise<string>;
